Drakflygaren/Drakflygaren/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Drakflygaren.Models
{
    public class Location
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string City { get; set; }

        public string Longitude { get; set; }

        public string Latitude { get; set; }

        public string CreatorId { get; set; }
        public virtual ApplicationUser Creator { get; set; }
    }
}

Drakflygaren/Drakflygaren/Models/LocationAction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Drakflygaren.Models
{
    public class LocationAction
    {
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        public int LocationId { get; set; }
        public virtual Location Location { get; set; }
    }
}

Drakflygaren/Drakflygaren/Models/LocationFavorite.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Drakflygaren.Models
{
    public class LocationFavorite : LocationAction
    {
        public int Id { get; set; }
    }
}

Drakflygaren/Drakflygaren/ViewModels/LocationViewModel.cs
using Drakflygaren.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Drakflygaren.ViewModels
{
    public class LocationViewModel
    {
        //Index
        public Location Location { get; set; }

        public bool Favorite { get; set; }

        public double Rating { get; set; }

        public int UserRating { get; set; }

        //Create
        [Required]
        [Display(Name = "Namn")]
        public string Name { get; set; }

        [Display(Name = "Plats")]
        public string Place { get; set; }

        [Required]
        [Display(Name = "Stad")]
        public string City { get; set; }

        [Required]
        public string Latitude { get; set; }

        [Required]
        public string Longitude { get; set; }
    }
}

Drakflygaren/Drakflygaren/Controllers/LocationsController.cs
using Drakflygaren.Models;
using Drakflygaren.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Drakflygaren.Controllers
{
    [Authorize]
    public class LocationsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var locationViewModels = new List<LocationViewModel>();

            foreach (var location in db.Locations.ToList())
            {
                locationViewModels.Add(GetLocationViewModel(location));               
            }

            return View(locationViewModels);
        }

        [AllowAnonymous]
        public ActionResult Details(int locationId)
        {
            return View(GetLocationViewModel(db.Locations.Find(locationId)));
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(LocationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();

                db.Locations.Add(new Location
                {
                    Name = model.Name,
                    City = model.City,
                    Latitude = model.Latitude,
                    Longitude = model.Longitude,
                    CreatorId = userId
                });

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? locationId)
        {
            if (locationId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(locationId);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,City,Longitude,Latitude,CreatorId")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? locationId)
        {
            if (locationId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(locationId);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int locationId)
        {
            Location location = db.Locations.Find(locationId);
            var locationFavorites = db.LocationFavorites.Where(lf => lf.LocationId == locationId);
            db.LocationFavorites.RemoveRange(locationFavorites);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult LocationFavorites()
        {
            var userId = User.Identity.GetUserId();
            var locationFavorites = db.LocationFavorites.Where(fl => fl.UserId == userId).ToList();

            return PartialView("_LocationFavorites", locationFavorites);
        }

        [HttpPost]
        public ActionResult ToggleFavorite(int locationId)
        {
            var userId = User.Identity.GetUserId();
            var locationFavorite = db.LocationFavorites.FirstOrDefault(fl => fl.UserId == userId && fl.LocationId == locationId);

            if (locationFavorite == null)
            {
                db.LocationFavorites.Add(new LocationFavorite { UserId = userId, LocationId = locationId });
            }

            else
            {
                db.LocationFavorites.Remove(locationFavorite);
            }

            db.SaveChanges();

            var locationFavorites = db.LocationFavorites.Include("Location").Include("User").Where(fl => fl.UserId == userId).ToList();
                
            return PartialView("_LocationFavorites", locationFavorites);
        }

        [HttpPost]
        public JsonResult RateLocation(int locationId, int rating)
        {
            var userId = User.Identity.GetUserId();
            var userLocationRating = db.LocationRatings.FirstOrDefault(lr => lr.LocationId == locationId && lr.UserId == userId);

            if (userLocationRating == null)
            {
                db.LocationRatings.Add(new LocationRating { LocationId = locationId, UserId = userId, Rating = rating });
            }

            else
            {
                if (userLocationRating.Rating == rating)
                {
                    db.LocationRatings.Remove(userLocationRating);
                }

                else
                {
                    userLocationRating.Rating = rating;
                }
            }

            db.SaveChanges();
            var locationRating = db.LocationRatings.Where(lr => lr.LocationId == locationId).Select(lr => lr.Rating).DefaultIfEmpty(0).Average();

            return Json(locationRating);
        }

        LocationViewModel GetLocationViewModel(Location location)
        {
            var userId = User.Identity.GetUserId();
            var userLocationRating = db.LocationRatings.FirstOrDefault(lr => lr.UserId == userId && lr.LocationId == location.Id);

            return new LocationViewModel
            {
                Location = location,
                Favorite = db.LocationFavorites.Any(fl => fl.UserId == userId && fl.LocationId == location.Id),
                Rating = db.LocationRatings.Where(lr => lr.LocationId == location.Id).Select(lr => lr.Rating).DefaultIfEmpty(0).Average(),
                UserRating = userLocationRating != null ? userLocationRating.Rating : 0
            };
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //public int Distance()
        //{
        //    var currentLocation;
        //    var favoritPlatsDistance;
        //    int distance = currentLocation
            
             
             
        //    return distance;
        //}
    }
}

Drakflygaren/Drakflygaren/Views/Locations/Create.cshtml
@model Drakflygaren.ViewModels.LocationViewModel

@{
    ViewBag.Title = "Create";
}

@section scripts {
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDOP-hCNyiygNNOURvqXC4A9VssSMieFGo&libraries=places"></script>
    <script src="~/Scripts/google-maps.autocomplete.js"></script>
}

<h2>Lägg till</h2>

@using (Html.BeginForm("Create", "Locations", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Longitude, new { id = "longitude" })
    @Html.HiddenFor(m => m.Latitude, new { id = "latitude" })

    <div class="form-group">
        @Html.LabelFor(m => m.Place, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(m => m.Place, new { htmlAttributes = new { id = "autocomplete", @class = "form-control" } })
        @Html.ValidationMessageFor(m => m.Place, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.City, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(m => m.City, new { htmlAttributes = new { id = "locality", @class = "form-control" } })
        @Html.ValidationMessageFor(m => m.City, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Name, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(m => m.Name, new { htmlAttributes = new { id = "route", @class = "form-control" } })
        @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <input type="submit" value="Lägg till plats" class="btn btn-success form-control" />
    </div>
}

Drakflygaren/Drakflygaren/Views/Locations/Delete.cshtml
@model Drakflygaren.Models.Location

@{
    ViewBag.Title = "Delete";
}

<h2>Ta bort @Model.Name</h2>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Creator.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator.Email)
        </dd>

        <dt>
            Namn
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Stad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>
    </dl>

    @using (Html.BeginForm(new { locationId = Model.Id })) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ta Bort" class="btn btn-danger" /> |
            @Html.ActionLink("Tillbaka", "Index")
        </div>
    }
</div>

Drakflygaren/Drakflygaren/Views/Locations/Details.cshtml
@model Drakflygaren.ViewModels.LocationViewModel

@{
    ViewBag.Title = Model.Location.Name;
}

<div class="row">
    <div data-id="@Model.Location.Id" class="@Html.AttributeEncode(Request.IsAuthenticated ? "col-md-9" : "col-md-12" ) map-item weather-item">
        <h2>
            <span class="locationName">@ViewBag.Title</span>

            @if (Request.IsAuthenticated)
            {
                <span class="pull-right">
                    <a class="toggle-favorite"><i class="fa @Html.AttributeEncode(Model.Favorite ? "fa-heart" : "fa-heart-o") text-danger"></i></a>
                </span>
            }
        </h2>

        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Redigera", "Edit", new { locationId = Model.Location.Id })
            <br />
            @Html.ActionLink("Ta Bort", "Delete", new { locationId = Model.Location.Id })
        }

        <h4>Stad: <span class="cityName">@Model.Location.City</span></h4>
        <p>Tillagd av: @Model.Location.Creator.UserName</p>
        <form hidden>
            <input class="cityLong" value="@Model.Location.Longitude" />
            <input class="cityLat" value="@Model.Location.Latitude" />

        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>Väder</th>
                    <th>&deg;C</th>
                    <th>Vind m/s</th>
                    <th>Vindriktning</th>
                    <th>Betyg</th>
                    @if (Request.IsAuthenticated)
                    {
                        <th>Betygsätt</th>
                    }
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><img alt="weather" class="weatherIcon" /></td>
                    <td class="cityTemp"></td>
                    <td class="cityWind"></td>
                    <td><span class="fa fa-location-arrow direction"></span></td>
                    <td class="location-rating">@Model.Rating</td>
                    @if (Request.IsAuthenticated)
                    {
                        <td>
                            @for (int i = 1; i <= 5; i++)
                            {
                                <a data-rating="@i" class="rate-location"><i class="fa @Html.AttributeEncode(Model.UserRating >= i ? "fa-star" : "fa-star-o") text-warning"></i></a>
                            }
                        </td>
                    }
                </tr>
            </tbody>
        </table>
        <div id="map_wrapper">
            <div id="map_canvas" class="mapping"></div>
        </div>
    </div>

    @if (Request.IsAuthenticated)
    {
        <div class="col-md-3">
            <h2>Favoriter</h2>
            <div id="favorite-locations">
                @Html.Action("LocationFavorites")
            </div>
        </div>
    }
</div>

@section scripts {
    <script src="~/Scripts/locations.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="~/Scripts/weather.js"></script>
    <script src="~/Scripts/google-maps.custom.js"></script>
}

Drakflygaren/Drakflygaren/Views/Locations/Edit.cshtml
@model Drakflygaren.Models.Location

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Plats</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CreatorId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

Drakflygaren/Drakflygaren/Views/Locations/Index.cshtml
@model IEnumerable<Drakflygaren.ViewModels.LocationViewModel>

@{
    ViewBag.Title = "Platser";
}

<div class="row">
    <div class="@Html.AttributeEncode(Request.IsAuthenticated ? "col-md-9" : "col-md-12" )">
        <h2>@ViewBag.Title <span class="pull-right"><button id="toggle-between-list-and-map" class="btn btn-primary">Lista / Karta</button></span></h2>
        <a href="@Url.Action("Create")"><i class="fa fa-plus"></i> Lägg till</a>
        <hr />
        <div id="locations-list">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Namn</th>
                        <th>Stad</th>
                        <th>Väder</th>
                        <th>&deg;C</th>
                        <th>Vind m/s</th>
                        <th>Betyg</th>
                        @if (Request.IsAuthenticated)
                        {
                            <th>Betygsätt</th>
                            <th>Favorit</th>
                            <th>Avstånd</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var locationViewModel in Model)
                    {
                        <tr data-id="@locationViewModel.Location.Id" class="weather-item map-item">
                            <td hidden>
                                <form>
                                    <input class="cityLong" value="@locationViewModel.Location.Longitude" />
                                    <input class="cityLat" value="@locationViewModel.Location.Latitude" />
                                </form>
                            </td>
                            <td><a class="locationName" href="@Url.Action("Details", new { locationId = locationViewModel.Location.Id })">@locationViewModel.Location.Name</a></td>
                            <td class="cityName">@locationViewModel.Location.City</td>
                            <td><img alt="weather" class="weatherIcon" /></td>
                            <td class="cityTemp"></td>
                            <td><span class="cityWind"></span> <span class="fa fa-location-arrow direction"></span></td>
                            <td class="location-rating">@locationViewModel.Rating</td>
                            @if (Request.IsAuthenticated)
                            {
                                <td>
                                    @for (int i = 1; i <= 5; i++)
                                    {
                                        <a data-rating="@i" class="rate-location"><i class="fa @Html.AttributeEncode(locationViewModel.UserRating >= i ? "fa-star" : "fa-star-o") text-warning"></i></a>
                                    }
                                </td>
                                <td><a class="toggle-favorite"><i class="fa @Html.AttributeEncode(locationViewModel.Favorite ? "fa-heart" : "fa-heart-o") text-danger"></i></a></td>
                                <td class="distance"></td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div id="locations-map" class="hide-content">
            <div id="map_wrapper">
                <div id="map_canvas" class="mapping"></div>
            </div>
        </div>
    </div>
    @if (Request.IsAuthenticated)
    {
        <div class="col-md-3">
            <h2>Favoriter</h2>
            <div id="favorite-locations">
                @Html.Action("LocationFavorites")
            </div>
        </div>
    }
</div>

@section scripts {
    <script src="~/Scripts/locations.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js"></script>
    <script src="~/Scripts/weather.js"></script>
    <script src="~/Scripts/google-maps.custom.js"></script>
}

Drakflygaren/Drakflygaren/Views/Locations/_LocationFavorites.cshtml
@model IEnumerable<Drakflygaren.Models.LocationFavorite>

<div class="list-group">
    @if (Model.Count() > 0)
    {
        foreach (var locationFavorite in Model)
        {

            <a data-id="@locationFavorite.LocationId" href="@Url.Action("Details", new { locationId = locationFavorite.LocationId })" class="list-group-item weather-item">
                <input class="cityLat" hidden value="@locationFavorite.Location.Latitude" />
                <input class="cityLong" hidden value="@locationFavorite.Location.Longitude" />
                <div><strong>@locationFavorite.Location.Name</strong><span class="pull-right"><img class="weatherIcon" alt="weather" /></span></div>
                <div>@locationFavorite.Location.City</div>
                <div>
                    <span class="cityTemp"></span>
                    <span>&deg;C</span><span class="pull-right">
                        <span class="cityWind"></span>
                        <span>m/s</span>
                        <span class="fa fa-location-arrow direction"></span>
                    </span>
                </div>
            </a>
        }
    }
    else
    {
        <p>Lägg till dina favoriter genom att trycka på hjärtat för aktuell rad i listan med platser</p>
    }
</div>