Drakflygaren/Drakflygaren/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Drakflygaren.Models
{
    public class Topic
    {
        public int TopicId { get; set; }

        [Display(Name = "Namn")]
        public string Name { get; set; }

        [Display(Name = "Beskrivning")]
        public string Description { get; set; }

        [Display(Name = "Skapad")]
        public DateTime CreatedOn { get; set; }

        //Foreign key
        public string UserId { get; set; }


        //Navigational Prop

        [ForeignKey("UserId")]
        public virtual ApplicationUser CreatedBy { get; set; }
        public virtual IList<TopicComment> Comments { get; set; }
        public virtual IList<TopicView> Views { get; set; }
        public virtual IList<TopicLike> TopicLikes { get; set; }

    }
}

Drakflygaren/Drakflygaren/Models/TopicAction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Drakflygaren.Models
{
    public class TopicAction
    {
        public int TopicId { get; set; }
        public virtual Topic Topic { get; set; }

        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

Drakflygaren/Drakflygaren/Models/TopicView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Drakflygaren.Models
{
    public class TopicView : TopicAction
    {
        public int Id { get; set; }

      
    }
}

Drakflygaren/Drakflygaren/ViewModels/TopicViewModel.cs
using Drakflygaren.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace Drakflygaren.ViewModels
{
    public class TopicViewModel
    {
        public Topic Topic { get; set; }

        public string Text { get; set; }

        public bool Liked { get; set; }
    }
}

Drakflygaren/Drakflygaren/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Drakflygaren.Models;
using Microsoft.AspNet.Identity;
using Drakflygaren.ViewModels;
using Drakflygaren.Helpers;

namespace Drakflygaren.Controllers
{
    public class TopicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Topics
        public ActionResult Index()
        {
            var topicViewModels = new List<TopicViewModel>();

            foreach (var topic in db.Topics.ToList())
            {
                topicViewModels.Add(GetTopicViewModel(topic));
            }
            ViewBag.User = User.Identity.Name;


            return View(topicViewModels);
        }

        private TopicViewModel GetTopicViewModel(Topic topic)
        {
            var userId = User.Identity.GetUserId();
            bool liked = db.TopicLikes.Any(tl => tl.TopicId == topic.TopicId && tl.UserId == userId);

            return new TopicViewModel { Topic = topic, Liked = liked };

        }

        // GET: Topics/Details/5
        public ActionResult Details(int? id, string message)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }

            var userId = User.Identity.GetUserId();

            if (!db.TopicViews.Any(tv => tv.UserId == userId && tv.TopicId == topic.TopicId) && userId != null)
            {
                db.TopicViews.Add(new TopicView { TopicId = topic.TopicId, UserId = userId });
                db.SaveChanges();
            }

            ViewBag.Message = message;
            return View(new TopicViewModel { Topic = topic });
        }

        [HttpPost]
        public ActionResult SendPost(TopicViewModel model)
        {
            var userId = User.Identity.GetUserId();
            db.TopicComments.Add(new TopicComment
            {
                Text = model.Text,
                TopicId = model.Topic.TopicId,
                UserId = userId,
                CommentDateTime = DateTime.Now,

            });

            db.SaveChanges();
            return RedirectToAction("Details", new { id = model.Topic.TopicId });


        }

        [HttpPost]
        public int TopicLike(int topicId)
        {
            var userId = User.Identity.GetUserId();
            var userTopicLike = db.TopicLikes.FirstOrDefault(tl => tl.TopicId == topicId && tl.UserId == userId);

            if (userTopicLike == null)
            {
                db.TopicLikes.Add(new TopicLike { UserId = userId, TopicId = topicId });
            }
            else
            {
                db.TopicLikes.Remove(userTopicLike);

            }
            db.SaveChanges();

            return db.TopicLikes.Where(tl => tl.TopicId == topicId).Count();
        }

        public ActionResult ReportPost(int reportedPostId, ReportCategory reportCategory)
        {
            var currentUserId = User.Identity.GetUserId();
            var message = string.Empty;

            //Bara kolla så att personen inte redan har anmält den här posten
            if (!db.Reports.Any(r => r.CommentId == reportedPostId && r.ReporterId == currentUserId))
            {
                //Här känns det ju helt rätt
                db.Reports.Add(new Report
                {
                    //Ändrade UserId till ReporterId för att EF ska fatta att det är en FK
                    //Hade självklart gått att ändra Reporter till User också..
                    //Annars måste man ange det manuellt [ForeignKey(Bla)]
                    ReporterId = currentUserId,
                    Category = reportCategory,
                    //Samma här CommentToReportId till CommentId
                    CommentId = reportedPostId
                });

                db.SaveChanges();
                message = "Kommentaren har blivit anmäld och kommer att åtgärdas så fort som möjligt";
            }

            else
            {
                message = "Du har redan anmält den här kommentaren";
            }

            //Ta fram postens topic så vi kan skicka tillbaka användaren till rätt ställe
            var topicId = db.TopicComments.Find(reportedPostId).TopicId;

            return RedirectToAction("Details", new { id = topicId, message = message });
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Topics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TopicId,Name,Description")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                topic.CreatedOn = DateTime.Now;
                topic.UserId = userId;


                db.Topics.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(topic);
        }

        // GET: Topics/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TopicId,Name,Description,CreatedOn,UserId")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(topic);
        }

        // GET: Topics/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Topic topic = db.Topics.Find(id);
            if (topic == null)
            {
                return HttpNotFound();
            }
            return View(topic);
        }

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Topic topic = db.Topics.Find(id);
            db.Topics.Remove(topic);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Drakflygaren/Drakflygaren/Views/Topics/Create.cshtml
@model Drakflygaren.Models.Topic

@{
    ViewBag.Title = "Create";
}

<h2>Skapa Ämne</h2>
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Skapa" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till lista", "Index")
</div>

Drakflygaren/Drakflygaren/Views/Topics/Delete.cshtml
@model Drakflygaren.Models.Topic

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Drakflygaren/Drakflygaren/Views/Topics/Details.cshtml
@using Drakflygaren.ViewModels
@using Drakflygaren.Helpers

@model TopicViewModel

@{
    ViewBag.Title = "Details";
}

<h4 class="text-warning">@ViewBag.Message</h4>
<h2>@Model.Topic.Name</h2>
<h4>@Model.Topic.Description<span class="pull-right">@Model.Topic.CreatedOn</span></h4>
<hr />
<div class="container list-group">

    @foreach (var comment in Model.Topic.Comments)
    {
        <div class="list-group-item">
            <div class="dropdown pull-right">
                <a data-toggle="dropdown" class="fa fa-exclamation-triangle"></a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink("Rasistiskt", "ReportPost", new { reportedPostId = comment.Id, reportCategory = ReportCategory.Rasistiskt })</li>
                    <li>@Html.ActionLink("Stötande", "ReportPost", new { reportedPostId = comment.Id, reportCategory = ReportCategory.Stötande })</li>
                </ul>
            </div>
            <span class="pull-right text-muted">@comment.User.UserName - @DragonHelper.GetTimeSpan(comment.CommentDateTime)</span>
            <p>@comment.Text</p>
        </div>
    }
</div>

<div>
    @using (Html.BeginForm("SendPost", "Topics", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m => m.Topic.TopicId)

        <div class="form-group">
            @Html.TextAreaFor(m => m.Text, new { @class = "form-control", rows = "5" })
        </div>

        <input type="submit" class="btn btn-success" />
    }
</div>
<hr />
<p>
    @Html.ActionLink("Tillbaka till forum", "Index")
</p>

Drakflygaren/Drakflygaren/Views/Topics/Edit.cshtml
@model Drakflygaren.Models.Topic

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Topic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TopicId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Drakflygaren/Drakflygaren/Views/Topics/Index.cshtml
@model IEnumerable<Drakflygaren.ViewModels.TopicViewModel>
@using Drakflygaren.Helpers

@{
    ViewBag.Title = "Forum";
}

@section scripts {
    <script src="~/Scripts/topic.js"></script>
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Skapa ny tråd", "Create")
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Namn</th>
            <th>Beskrivning</th>
            <th>Senaste inlägget</th>
            <th>Kommentarer</th>
            <th>Visningar</th>
            <th>Skapad av</th>
            @if (User.Identity.IsAuthenticated)
            {
            <th>Gilla</th>
            }
            <th><span class="fa fa-thumbs-up"></span></th>
            <th></th>

        </tr>
    </thead>
    <tbody>


        @foreach (var topicViewModel in Model)
        {
            <tr data-id="@topicViewModel.Topic.TopicId">
                <td>@Html.ActionLink(topicViewModel.Topic.Name, "Details", new { id = topicViewModel.Topic.TopicId })</td>
                <td>@topicViewModel.Topic.Description</td>
                <td>@(topicViewModel.Topic.Comments.Any() ? DragonHelper.GetTimeSpan(topicViewModel.Topic.Comments.Last().CommentDateTime) : "-")</td>
                <td>@topicViewModel.Topic.Comments.Count</td>
                <td>@topicViewModel.Topic.Views.Count</td>
                <td>@topicViewModel.Topic.CreatedBy.UserName</td>

                @if (User.Identity.IsAuthenticated)
                {
                    <td><a class="like-topic-button"><i class="fa @Html.AttributeEncode(topicViewModel.Liked ? "fa-thumbs-up" : "fa-thumbs-o-up")"></i></a></td>
                }
                <td class="topic-likes-count">@topicViewModel.Topic.TopicLikes.Count</td>
                <td>
                    @if (User.IsInRole("Admin") || User.Identity.Name == topicViewModel.Topic.CreatedBy.UserName)
                    {
                        @Html.ActionLink("Delete", "Delete", new { id = topicViewModel.Topic.TopicId })
                    }
                </td>


            </tr>




        }
    </tbody>
</table>